name: 定时同步docker镜像

on:
  #推送的时候跑
  push:
  #star的时候触发备份
  watch:
    types: started
  schedule:
    # 3个小时备份一次
    - cron:  '0 */3 * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Settings env
        run: echo "NOW=$(date +'%Y-%m-%dT%H:%M:%S')" >> $GITHUB_ENV

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          skopeo --version
          echo '${{ env.NOW }}'
